name: Bug Report
description: File a Bug!
title: '[Bug]: '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to contribute!
  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      description: Describe what function is not working as expected?
      placeholder:
        'ex. the sleep function does not work as expected, it throws
        ReferenceError in Node 12'
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What is the expected outcome?
      placeholder: ex. sleep(1000) should resolve after 1 second.
    validations:
      required: true
  - type: textarea
    id: current_behavior
    attributes:
      label: Actual Behavior
      description: What is the current behavior?
      placeholder: ex. sleep(1000) resolves after 1000 second.
    validations:
      required: true
